version: "3.9"

services:
  backend:
    build: ./backend
    container_name: campaign-backend-dev
    working_dir: /app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir . --reload-exclude outputs/* --reload-exclude .git/* --reload-exclude venv/* --reload-exclude .venv/* --reload-exclude __pycache__/*
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - outputs:/app/outputs
    restart: unless-stopped
    networks:
      - campaign-network-dev

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: campaign-frontend-dev
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - campaign-network-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  outputs:

networks:
  campaign-network-dev:
    driver: bridge 