version: "3.9"
services:
  api:
    build: .
    container_name: campaign-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped 