version: "3.9"
services:
  api:
    build: .
    container_name: campaign-api
    working_dir: /app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir . --reload-exclude outputs/* --reload-exclude .git/* --reload-exclude venv/* --reload-exclude .venv/* --reload-exclude __pycache__/*
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./:/app
      - outputs:/app/outputs
    restart: unless-stopped

volumes:
  outputs: 